## Numpy Fundamentals

### 📝 Array Creation 

In [12]:
# Creating NumPy Array: np.Array()
import numpy as np
array = np.array([1,2,3,4])
print (array)
array
# b = 6
# b


# arr1 = np.array([1, 2, 3, 4, 5])
# print("1D Array:", arr1)



[1 2 3 4]


array([1, 2, 3, 4])

In [25]:
# Creating NumPy Array with Data Type dtype = datatype
# size = data size shape = kasto shape ko xa ndim - dimension
# itemsize= kati size ko xa each item
# astype str = array string ma convert gareko ho 
array.dtype
# array.size
# array.shape
# array.ndim
# array.itemsize
# array.astype(str)

dtype('int64')

In [39]:
# Creating NumPy Array using np.Arange() and reshape()
array = np.arange(1,9)
array.reshape(4,2)


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [48]:
# np.ones and np.zeros
array = np.ones((3,4), int)
print(array)
array.dtype


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


dtype('int64')

In [55]:
# np.random
arr = np.random.random(3)
arr

array([0.75886016, 0.00556091, 0.68788785])

 linearly spaced array- np.linspace()

5

In [58]:
# Identity Matrix Creation 

I = np.identity(3)   # 3x3 identity matrix
print(I)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [64]:
# NumPy Attributes (dtype, size, shape, itemsize, ndim)
I.dtype
I.size
I.shape
I.itemsize
I.ndim


2

In [68]:
# Changing Datatype - astype
I.astype(int)



[[1 0 0]
 [0 1 0]
 [0 0 1]]


### 📝 NumPy Array Functions

In [82]:
# Max/Min/Sum/Prod
array = np.array([4,16,9,8,11,14])
array
array.max()
arrray.sum()
array.min()
array.prod()

np.int64(709632)

In [87]:
#  Mean, Standard Deviation, Variance 
# array.mean()
# array.std()
array.var()


np.float64(15.555555555555557)

In [90]:
# Arrays Dot Product
arr1 = np.arange(1,13).reshape((3,4))
arr2 = np.arange(12,24).reshape((4,3))
print(np.dot(arr1,arr2))
print(arr1@arr2)


[[180 190 200]
 [444 470 496]
 [708 750 792]]
[[180 190 200]
 [444 470 496]
 [708 750 792]]


In [95]:
# Log and Exp function
a = np.arange(1,4)
a
# np.log(a)
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [55]:
# Difference between round floor and ceil
import numpy as np

# Sample array
arr = np.array([3.2, 4.7, -2.5, -3.8])

print("Original Array:", arr)

# Round to nearest integer
print("Round:", np.round(arr,5))

# Floor (always down)
print("Floor:", np.floor(arr))

# Ceil (always up)
print("Ceil:", np.ceil(arr))

Original Array: [ 3.2  4.7 -2.5 -3.8]
Round: [ 3.2  4.7 -2.5 -3.8]
Floor: [ 3.  4. -3. -4.]
Ceil: [ 4.  5. -2. -3.]


In [2]:
# Indexing Slicing (Already Covered in Lecture in depth)
import numpy as np
arr1 = np.arange(10)
print("First element:", arr1[0])
print("Last element:", arr1[-1])

# Slicing
print("First 5 elements:", arr1[:5])
print("Elements from index 3 to 7:", arr1[3:8])

arr2 = np.arange(12).reshape((3,4))
print("\narr2:\n", arr2)

# Indexing
print("Element at row 1, col 2:", arr2[1,2])   # second row, third column

# Slicing rows and columns
print("First row:", arr2[0,:])
print("First column:", arr2[:,0])
print("Submatrix (rows 0-1, cols 1-2):\n", arr2[0:2, 1:3])

arr2 = np.arange(8).reshape((2,2,2))
# 3D Array
arr3 = np.arange(8).reshape((2,2,2))
print("\narr3:\n", arr3)

# Indexing
print("Element at [1,0,1]:", arr3[1,0,1])

# Slicing
print("First block:\n", arr3[0])
print("Second block:\n", arr3[1])


First element: 0
Last element: 9
First 5 elements: [0 1 2 3 4]
Elements from index 3 to 7: [3 4 5 6 7]

arr2:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at row 1, col 2: 6
First row: [0 1 2 3]
First column: [0 4 8]
Submatrix (rows 0-1, cols 1-2):
 [[1 2]
 [5 6]]

arr3:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Element at [1,0,1]: 5
First block:
 [[0 1]
 [2 3]]
Second block:
 [[4 5]
 [6 7]]


In [109]:
# reshape
import numpy as np

# Create a 1D array with 12 elements
arr = np.arange(12)
print("Original 1D Array:", arr)

# Reshape into 2D (3 rows, 4 columns)
arr2 = arr.reshape(3, 4)
print("\nReshaped to 3x4:\n", arr2)

# Reshape into 2D (4 rows, 3 columns)
arr3 = arr.reshape(4, 3)
print("\nReshaped to 4x3:\n", arr3)

# Reshape into 3D (2 blocks, 2 rows, 3 columns)
arr4 = arr.reshape(2, 2, 3)
print("\nReshaped to 3D (2x2x3):\n", arr4)


Original 1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to 4x3:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Reshaped to 3D (2x2x3):
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [6]:
# Transpose 
array = np.arange(1,9).reshape(2,4)
array
array.transpose()
# array.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [9]:
# ravel or flatten 
array
print(array.ravel())
array.flatten()
# duitei ko kaam 2d array lai 1d banaune raixa 



[1 2 3 4 5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
# Stacking - horizonal Stacking
arr1 = np.arange(0,12).reshape((3,4))
arr2 = np.arange(12,24).reshape((3,4))

print("arr1:\n", arr1)
print("arr2:\n", arr2)

# Horizontal stacking
hstacked = np.hstack((arr1, arr2))
print("\nHorizontally Stacked Array:\n", hstacked)# horizontally array lai joddinx 01231213 garera


arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr2:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Horizontally Stacked Array:
 [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [11]:
# Stacking - vertical Stacking
arr1 = np.arange(0,12).reshape((3,4))
arr2 = np.arange(12,24).reshape((3,4))

print("arr1:\n", arr1)
print("arr2:\n", arr2)

# Vertical stacking
vstacked = np.vstack((arr1, arr2))
print("\nVertically Stacked Array:\n", vstacked)

arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr2:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Vertically Stacked Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [16]:
# Splitting - Vertical Splitting 
arr1 = np.arange(0,16).reshape((4,4))
print(arr1)
[arr3,arr2] = np.vsplit(arr1,2)
print(arr3)
arr2


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]


array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
# Horizontal Splitting
arr1 = np.arange(0,16).reshape((4,4))
print(arr1)
[arr2,arr3] = np.hsplit(arr1,2)

print( arr3)
arr2


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [23]:
# Understanding Views
arra = np.arange(1,10)
arra2 = arra
print(arra)
print(arra2)
arra2[0] = 100
print(arra)
print(arra2)
#view bhaneko same dekhine jasto banaunu tara gareko change will be applied on real array

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[100   2   3   4   5   6   7   8   9]
[100   2   3   4   5   6   7   8   9]


In [26]:
# Understanding Copies
ajju = np.arange(10,15)
ajju1 = ajju.copy()
print(ajju)
print(ajju1)
ajju1[2] = 50
print(ajju)
    
print(ajju1)


[10 11 12 13 14]
[10 11 12 13 14]
[10 11 12 13 14]
[10 11 50 13 14]


### 📝 Challenging Section 

#### 1. Create a vector of zeros of size 10 but the fifth value should be 1.

In [31]:
# Code here 
arra = np.zeros(10,int)
arra[4] = 1
arra

  


array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 2. Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) <br> and print the array and avg of the array.





In [19]:
# Code here
a = int(input("Enter the number of row (A): "))
b = int(input("Enter the number of columns (B): "))

arr = np.random.rand(a,b)
print("\n Random array:\n", arr)




Enter the number of row (A):  2
Enter the number of columns (B):  2



 Random array:
 [[0.53581289 0.53660806]
 [0.48704046 0.07354262]]


#### 3. Create a 2d array with 1 on the border and 0 inside. 

In [20]:
# Code here
import numpy as np

# Define size of the array
n = 4 # you can change this to any size that you want to create 
# n ko value user sanga magna pani sakiyo
# Create an array of zeros
arr = np.zeros((n, n), dtype=int)

# Set the border values to 1
arr[0, :] = 1        # first row
arr[-1, :] = 1       # last row
arr[:, 0] = 1        # first column
arr[:, -1] = 1       # last column

print( arr)




[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


#### 4. Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [4]:
# Code here


# Create vector of size 10, values between 0 and 1 (excluded)
arr = np.linspace(0, 1, 12, endpoint=False)[1:-1]  # generate extra points, then slice
print("Vector:", arr)


Vector: [0.08333333 0.16666667 0.25       0.33333333 0.41666667 0.5
 0.58333333 0.66666667 0.75       0.83333333]


#### 5. Can you create a identity mattrix of shape (3,4). If yes write code for it

In [22]:
# Code here
import numpy as np

# Create a rectangular identity-like matrix (3x4)
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


#### 6. Create a 5x5 matrix with row values ranging from 0 to 4.

In [27]:
# Code here
import numpy as np

# Each row should be [0,1,2,3,4]
matrix = np.tile(np.arange(5), (5,1))
print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 7. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [11]:
# Code 
import numpy as np

arr = np.arange(6*7*8).reshape(6,7,8)
index = 99  # 100th element (0-based)
coords = np.unravel_index(index, arr.shape)
print("Index of 100th element:", coords)
 



Index of 100th element: (np.int64(1), np.int64(5), np.int64(3))


#### 8. Provided a numpy array, your task is to print a reversed NumPy array with the element type float.

In [16]:
# Code here
arr = np.arange(5)
reversed_arr = arr[::-1].astype(float)

print("Original Array:", arr)
print("Reversed Float Array:", reversed_arr)





Original Array: [0 1 2 3 4]
Reversed Float Array: [4. 3. 2. 1. 0.]


#### 9. Count the number of elements of a numpy array.

In [17]:
# Code here 

import numpy as np

# Example array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Count elements
count = arr.size

print("Array:\n", arr)
print("Number of elements:", count)


Array:
 [[1 2 3]
 [4 5 6]]
Number of elements: 6


#### 10. Write a python function that accepts infinite number of numpy arrays <br> and do the vertical stack to them. Then return that new array as result.

In [35]:
import numpy as np


arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
arr3 = np.array([[7, 8]])


stacked = np.vstack((arr1, arr2, arr3))
print("Vertically Stacked Array:\n", stacked)

Vertically Stacked Array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### 11. Swap column-1 of array with column-2 in the array.

In [49]:
# Code here
arru = np.arange(12)
arru = arru.reshape(3,4)
print(arru)
arru[:, [0, 1]] = arru[:, [1, 0]]
arru




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 1,  0,  2,  3],
       [ 5,  4,  6,  7],
       [ 9,  8, 10, 11]])

#### 12. Replace odd elements in arrays with -1.

In [34]:
# Code here
arr = np.arange(10)
arr [arr%2 == 1 ]= -1
arr




array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### 13.  Given two arrays of same shape make an array of max out of two arrays. (Numpy way)

In [51]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
np.maximum(a,b)



array([6, 3, 1, 7, 8])

#### 14. Create the following pattern without hardcoding. 

In [54]:
# Code here
a = np.array([1, 2, 3])

part1 = np.repeat(a, 3)

part2 = np.tile(a, 3)

arr = np.concatenate([part1, part2])
print(arr)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


**Happy Coding 🎉🎉**