# Numpy Tuttorial 

In [1]:
import numpy as np

In [14]:
myarr = np.array([[1,2,3,4,5]])

In [12]:
myarr

array([1, 2, 3, 4, 5], dtype=int8)

In [15]:
myarr.shape

(1, 5)

In [16]:
myarr.dtype

dtype('int64')

In [17]:
myarr.ndim

2

In [18]:
myarr[0,1]

np.int64(2)

In [19]:
myarr[0,1] = 44

In [20]:
myarr[0,1]

np.int64(44)

In [21]:
myarr

array([[ 1, 44,  3,  4,  5]])

# Creating Numpy Array from python other structures

In [25]:
listArray = np.array([[1,2,3,], [5,6,7], [8,9,0]])

In [26]:
listArray

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [27]:
listArray.dtype

dtype('int64')

In [28]:
listArray.size

9

In [29]:
listArray.ndim

2

In [30]:
listArray.shape

(3, 3)

In [31]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

# Intrinsic Numpy Creation Array

In [36]:
zero = np.zeros((2,5))

In [37]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
arr = np.arange(1,15)

In [39]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
lispace = np.linspace(1,15,3)

In [43]:
lispace

array([ 1.,  8., 15.])

In [44]:
emp = np.empty((4,5))

In [45]:
emp

array([[1.16635994e-311, 6.22522714e-322, 0.00000000e+000,
        0.00000000e+000, 2.37663529e-312],
       [1.15998412e-028, 4.31603868e-080, 1.94919985e-153,
        1.35717430e+131, 7.06652016e-096],
       [7.06652016e-096, 1.81148490e-152, 9.37041222e-076,
        6.98345624e-077, 6.98345624e-077],
       [1.06239598e-153, 3.98472821e+252, 1.06244660e-153,
        9.78750380e+199, 6.97843734e+252]])

In [46]:
emplike = np.empty_like(lispace)

In [47]:
emplike

array([ 1.,  8., 15.])

In [48]:
arr = np.arange(99)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [50]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [53]:
arr.reshape(99)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [54]:
arr.dtype

dtype('int64')

In [55]:
arr.size

99

In [56]:
arr.shape

(99,)

In [57]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [59]:
arr.shape

(99,)

# Axis concept of Numpy

In [5]:
import numpy as np
x = [[1,2,3,], [4,5,6], [7,1,0]]

In [6]:
arr = np.array(x)

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [8]:
arr.sum(axis = 0)

array([12,  8,  9])

In [9]:
arr.sum(axis = 1)

array([ 6, 15,  8])

In [10]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [33]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 7]])

In [16]:
arr.flat

# Different function of numpy

In [14]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [15]:
arr.ndim

2

In [17]:
arr.size

9

In [18]:
arr.shape

(3, 3)

In [19]:
arr.nbytes

72

In [20]:
arr.dtype

dtype('int64')

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 7]])

In [27]:
arr.argmin()

np.int64(8)

In [28]:
arr.argmax()

np.int64(6)

In [31]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 7]])

In [34]:
arr[0:1]

array([[1, 2, 3]])

In [35]:
arr[1:1]


array([], shape=(0, 3), dtype=int64)

In [36]:
arr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr[1]

array([4, 5, 6])

In [38]:
arr[2:1]

array([], shape=(0, 3), dtype=int64)

In [40]:
arr[2]

array([0, 1, 7])

In [41]:
arr[2,0]

np.int64(0)

In [42]:
arr[2,0] = 7

In [43]:
arr[2,2] = 0

In [44]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [45]:
arr.argmax(axis=1)

array([2, 2, 0])

In [46]:
arr.argmax(axis = 0)

array([2, 1, 1])

In [47]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

# Working with 1d array

In [21]:
one = np.array([1,2,3,4,5,555])

In [22]:
one

array([  1,   2,   3,   4,   5, 555])

In [23]:
one.argmax()

np.int64(5)

In [24]:
one.argmin()

np.int64(0)

In [25]:
one.argsort()

array([0, 1, 2, 3, 4, 5])

In [50]:
one.argsort()

array([0, 1, 2, 3, 4, 5])

In [51]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [52]:
arr.reshape([9,1])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

# Mathematical operations on numpy array

In [53]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
arr2 = np.array([[1,2,3],
                [3,2,1],
                [0,1,2]])

In [56]:
arr2

array([[1, 2, 3],
       [3, 2, 1],
       [0, 1, 2]])

In [57]:
arr + arr2

array([[2, 4, 6],
       [7, 7, 7],
       [7, 2, 2]])

In [58]:
arr - arr2

array([[ 0,  0,  0],
       [ 1,  3,  5],
       [ 7,  0, -2]])

In [59]:
arr * arr2

array([[ 1,  4,  9],
       [12, 10,  6],
       [ 0,  1,  0]])

In [60]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [62]:
arr.sum()

np.int64(29)

In [63]:
arr.min()

np.int64(0)

In [64]:
arr.max()

np.int64(7)